window.PORTFOLIO_DATA = {
    "en": [
        {
            "Rank": 1,
            "Ticker": "SIVE.ST",
            "Name": "Sivers Semiconductors",
            "EV Upside": 438,
            "Base": 92,
            "Port": "✓",
            "Current Price": 63.35,
            "Upside": "5.8x",
            "Position Type": "🔒 CHOKEPOINT\nPhysics: CW laser — silicon cannot generate light. Every CPO gen. 2026-2035+",
            "Artifact Updated": "Jun 15 (305M verified, V11 AMD, no pre-dilution)",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": 126,
            "FY2028": 365,
            "FY2029": 598,
            "FY2030": 810,
            "Change %": "-13.64%",
            "Entry": 118,
            "Total": 102
        },
        {
            "Rank": 2,
            "Ticker": "3363.TWO",
            "Name": "FOCI (上詮)",
            "EV Upside": 410,
            "Base": 81,
            "Port": "✓",
            "Current Price": 575.0,
            "Upside": "6.1x",
            "Position Type": "⚡ Bottleneck",
            "Artifact Updated": "Jun 10 (scrub)",
            "SuperCycle": "AI, CPO",
            "FY2027": "1,307",
            "FY2028": "3,484",
            "FY2029": "5,728",
            "FY2030": "7,963",
            "Change %": "-4.40%",
            "Entry": 121,
            "Total": 97
        },
        {
            "Rank": 3,
            "Ticker": "LPK.DE",
            "Name": "LPKF Laser & Electronics",
            "EV Upside": 409,
            "Base": 83,
            "Port": "✓",
            "Current Price": 21.1,
            "Upside": "5.9x",
            "Position Type": "🔒 CHOKEPOINT\nPhysics: LIDE glass TGV — organic cannot support next-gen. Triple supercycle: DB5 AI packaging + DB3 LEO Space (SpaceX) + DB8 Defense. 2027-2035+",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI, CPO",
            "FY2027": 54,
            "FY2028": 125,
            "FY2029": 243,
            "FY2030": 386,
            "Change %": "-1.80%",
            "Entry": 119,
            "Total": 97
        },
        {
            "Rank": 4,
            "Ticker": "005930.KS",
            "Name": "Samsung Electronics",
            "EV Upside": 325,
            "Base": 90,
            "Port": "✓",
            "Current Price": 339000.0,
            "Upside": "4.6x",
            "Position Type": "🔒 CHOKEPOINT\nArchitectural: Only non-US foundry+memory for China. Samsung = default Chinese AI partner. 2026-2030+",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI",
            "FY2027": 1289000,
            "FY2028": 1563000,
            "FY2029": 1754000,
            "FY2030": 1889000,
            "Change %": "+3.88%",
            "Entry": 106,
            "Total": 96
        },
        {
            "Rank": 5,
            "Ticker": "8147.TWO",
            "Name": "Nextronics Engineering",
            "EV Upside": 325,
            "Base": 70,
            "Port": "",
            "Current Price": 137.0,
            "Upside": "5.6x",
            "Position Type": "⚡ Bottleneck",
            "Artifact Updated": "Jun 10 (restructure)",
            "SuperCycle": "AI, CPO",
            "FY2027": "234",
            "FY2028": "774",
            "FY2029": "1,709",
            "FY2030": "2,703",
            "Change %": "+0.79%",
            "Entry": 100,
            "Total": 82
        },
        {
            "Rank": 6,
            "Ticker": "000660.KS",
            "Name": "SK Hynix",
            "EV Upside": 255,
            "Base": 93,
            "Port": "✓",
            "Current Price": 2670000.0,
            "Upside": "3.7x",
            "Position Type": "🔒 CHOKEPOINT\nArchitectural: #1 HBM — 4nm logic base die lead widens each gen. Memory architecture permanent. 2026-2030+",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI",
            "FY2027": 8322000,
            "FY2028": 9986000,
            "FY2029": 11654000,
            "FY2030": 12899000,
            "Change %": "+1.15%",
            "Entry": 94,
            "Total": 93
        },
        {
            "Rank": 7,
            "Ticker": "ALRIB",
            "Name": "Riber SA (MBE equipment)",
            "EV Upside": 240,
            "Base": 70,
            "Port": "",
            "Current Price": 11.3,
            "Upside": "4.4x",
            "Position Type": "🔒 CHOKEPOINT\nPhysics: MBE equipment for QD lasers + ROSIE SiPh + quantum materials. 2027-2035+",
            "Artifact Updated": "Jun 10 (restructure)",
            "SuperCycle": "AI, CPO",
            "FY2027": "33",
            "FY2028": "50",
            "FY2029": "72",
            "FY2030": "106",
            "Change %": "-3.42%",
            "Entry": 100,
            "Total": 82
        },
        {
            "Rank": 8,
            "Ticker": "XFAB",
            "Name": "X-Fab Silicon Foundries",
            "EV Upside": 233,
            "Base": 77,
            "Port": "",
            "Current Price": 8.0,
            "Upside": "4.0x",
            "Position Type": "WL",
            "Artifact Updated": "Jun 10 (restructure)",
            "SuperCycle": "AI, CPO, 800G",
            "FY2027": "18.47",
            "FY2028": "32.21",
            "FY2029": "50.69",
            "FY2030": "71.45",
            "Entry": 100,
            "Total": 86
        },
        {
            "Rank": 9,
            "Ticker": "MU",
            "Name": "Micron Technology",
            "EV Upside": 216,
            "Base": 88,
            "Port": "✓",
            "Current Price": 1132.33,
            "Upside": "3.5x",
            "Position Type": "⚡ BOTTLENECK\nSupply: #3 HBM — supply/demand imbalance temporary. China banned limits TAM. 1-3yr window.",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI",
            "FY2027": 2842,
            "FY2028": 3908,
            "FY2029": 4855,
            "FY2030": 5684,
            "Change %": "-2.99%",
            "Entry": 86,
            "Total": 87
        },
        {
            "Rank": 10,
            "Ticker": "AAOI",
            "Name": "Applied Optoelectronics",
            "EV Upside": 218,
            "Base": 74,
            "Port": "✓",
            "Current Price": 135.69,
            "Upside": "4.0x",
            "Position Type": "⚡ BOTTLENECK\nCapacity: Transceiver assembly — capacity expanding to 500K/mo. Competitive market. 1-2yr window.",
            "Artifact Updated": "Jun 10 (restructure) +Jun13 ATM/share fix +Jun13 VI correction +AXT/Nov10",
            "SuperCycle": "AI, 1.6T, 800G",
            "FY2027": "272",
            "FY2028": "536",
            "FY2029": "671",
            "FY2030": "581",
            "Change %": "-11.85%",
            "Entry": 99,
            "Total": 84
        },
        {
            "Rank": 11,
            "Ticker": "NBIS",
            "Name": "Nebius Group",
            "EV Upside": 192,
            "Base": 83,
            "Port": "",
            "Current Price": 240.3,
            "Upside": "3.3x",
            "Position Type": "⚡ Bottleneck",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI",
            "FY2027": 291,
            "FY2028": 795,
            "FY2029": 1252,
            "FY2030": 1685,
            "Change %": "-9.42%",
            "Entry": 83,
            "Total": 83
        },
        {
            "Rank": 12,
            "Ticker": "IQE.L",
            "Name": "IQE plc",
            "EV Upside": 185,
            "Base": 77,
            "Port": "",
            "Current Price": 46.8,
            "Upside": "3.4x",
            "Position Type": "⚡ BOTTLENECK\nCatalyst: M&A strategic review — event-driven, not structural. Single trigger. 6-12mo window.",
            "Artifact Updated": "Jun 15 (InP+TSEM+margin)",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": 77,
            "FY2028": 159,
            "FY2029": 187,
            "FY2030": 205,
            "Change %": "-15.00%",
            "Entry": 85,
            "Total": 80
        },
        {
            "Rank": 13,
            "Ticker": "6451.TW",
            "Name": "ShunSin Technology",
            "EV Upside": 172,
            "Base": 82,
            "Port": "✓",
            "Current Price": 598.0,
            "Upside": "3.1x",
            "Position Type": "🔒 CHOKEPOINT\nArchitectural: CPO packaging — Foxconn FAU alignment for optical engines. 2027-2032+",
            "Artifact Updated": "Jun 27 (v4.2: TSMC COUPE confirmed, Base 88→82%, decomposed margins)",
            "SuperCycle": "AI, CPO",
            "FY2027": 886,
            "FY2028": 1849,
            "FY2029": 2859,
            "FY2030": 3915,
            "Change %": "-9.88%",
            "Entry": 77,
            "Total": 80
        },
        {
            "Rank": 14,
            "Ticker": "AMPX",
            "Name": "Amprius Technologies",
            "EV Upside": 169,
            "Base": 75,
            "Port": "",
            "Current Price": 12.91,
            "Upside": "3.3x",
            "Position Type": "🔒 CHOKEPOINT\nPhysics+Reg: 500 Wh/kg no competitor within 2x + NDAA regulatory moat. 2026-2035+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "21",
            "FY2028": "42",
            "FY2029": "68",
            "FY2030": "101",
            "Change %": "-7.83%",
            "Entry": 81,
            "Total": 77
        },
        {
            "Rank": 15,
            "Ticker": "SNDK",
            "Name": "SanDisk Corp",
            "EV Upside": 155,
            "Base": 87,
            "Port": "✓",
            "Current Price": 2090.71,
            "Upside": "2.8x",
            "Position Type": "⚡ BOTTLENECK\nSupply: NAND shortage — new fabs coming (Samsung P5, SK Hynix China). Through H1 2027.",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI",
            "FY2027": 4025,
            "FY2028": 5822,
            "FY2029": 7452,
            "FY2030": 8815,
            "Change %": "-4.75%",
            "Entry": 70,
            "Total": 80
        },
        {
            "Rank": 16,
            "Ticker": "SOI.PA",
            "Name": "Soitec SA",
            "EV Upside": 132,
            "Base": 87,
            "Port": "",
            "Current Price": 114.35,
            "Upside": "2.5x",
            "Position Type": "🔒 CHOKEPOINT\nIP: >95% Photonics-SOI, 3,500+ Smart Cut patents\nSiN = complement (dismissed). Fungible capacity RF→Photonics.",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": "148",
            "FY2028": "288",
            "FY2029": "653",
            "FY2030": "1,342",
            "Change %": "-6.31%",
            "Entry": 63,
            "Total": 77
        },
        {
            "Rank": 17,
            "Ticker": "AEHR",
            "Name": "Aehr Test Systems",
            "EV Upside": 86,
            "Base": 93,
            "Port": "",
            "Current Price": 91.81,
            "Upside": "1.9x",
            "Position Type": "🔒 CHOKEPOINT\nPhysics: Sole-source WLBI — no competitor exists. Every compound semi. 2026-2035+",
            "Artifact Updated": "Jun 11 (restructure) +Nov10",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": "80",
            "FY2028": "177",
            "FY2029": "261",
            "FY2030": "321",
            "Change %": "-14.14%",
            "Entry": 45,
            "Total": 74
        },
        {
            "Rank": 18,
            "Ticker": "FTC.L",
            "Name": "Filtronic PLC",
            "EV Upside": 86,
            "Base": 80,
            "Port": "",
            "Current Price": 230.0,
            "Upside": "2.1x",
            "Position Type": "🔒 CHOKEPOINT\nPhysics: E-band GaN SSPA monopoly + V-band consumer terminal TAM (SpaceX funded R&D). Capacity lock-out blocks Amazon. Golden Dome #1 contractor link. 2026-2035+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, Other",
            "FY2027": "213",
            "FY2028": "477",
            "FY2029": "864",
            "FY2030": "1,379",
            "Change %": "+1.48%",
            "Entry": 52,
            "Total": 69
        },
        {
            "Rank": 19,
            "Ticker": "LITE",
            "Name": "Lumentum Holdings",
            "EV Upside": 80,
            "Base": 82,
            "Port": "",
            "Current Price": 816.98,
            "Upside": "2.0x",
            "Position Type": "🔒 CHOKEPOINT\nPhysics: EML laser near-monopoly — capacity sold out to 2029. 2026-2030+",
            "Artifact Updated": "Jun 11 (restructure) +Jun12 InP fold +Nov10",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": "980",
            "FY2028": "1,615",
            "FY2029": "2,241",
            "FY2030": "2,882",
            "Change %": "-8.61%",
            "Entry": 49,
            "Total": 69
        },
        {
            "Rank": 20,
            "Ticker": "3105.TW",
            "Name": "Win Semiconductors",
            "EV Upside": 84,
            "Base": 82,
            "Port": "",
            "Current Price": 424.0,
            "Upside": "2.0x",
            "Position Type": "⚡ Bottleneck",
            "Artifact Updated": "Jun 11 (restructure) +Nov10",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": "513",
            "FY2028": "858",
            "FY2029": "1,128",
            "FY2030": "1,369",
            "Change %": "-1.31%",
            "Entry": 51,
            "Total": 70
        },
        {
            "Rank": 21,
            "Ticker": "688596.SH",
            "Name": "正帆科技 Gentech",
            "EV Upside": 81,
            "Base": 73,
            "Port": "",
            "Current Price": 65.95,
            "Upside": "2.1x",
            "Position Type": "📊 BENEFICIARY\nChina fab gas/chemical + WFE subsystem + OPEX platform",
            "Artifact Updated": "Jun 27 (new dive, fab infrastructure + Gas Box + quartz/SiC + precursors)",
            "SuperCycle": "AI, WFE Subsystems, Gas/Chemical, 国産替代",
            "FY2027": 68,
            "FY2028": 139,
            "FY2029": 219,
            "FY2030": 293,
            "Entry": 53,
            "Total": 65
        },
        {
            "Rank": 22,
            "Ticker": "000636.SZ",
            "Name": "Fenghua Advanced (风华高科)",
            "EV Upside": 76,
            "Base": 80,
            "Port": "",
            "Current Price": 78.5,
            "Upside": "1.9x",
            "Position Type": "WL",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI",
            "FY2027": 81,
            "FY2028": 153,
            "FY2029": 191,
            "FY2030": 209,
            "Entry": 47,
            "Total": 67
        },
        {
            "Rank": 23,
            "Ticker": "BRUN",
            "Name": "Boost Run",
            "EV Upside": 83,
            "Base": 68,
            "Port": "",
            "Current Price": 34.23,
            "Upside": "2.2x",
            "Position Type": "",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI",
            "FY2027": "39",
            "FY2028": "76",
            "FY2029": "112",
            "FY2030": "150",
            "Entry": 56,
            "Total": 63
        },
        {
            "Rank": 24,
            "Ticker": "4078.T",
            "Name": "Sakai Chemical (堺化学)",
            "EV Upside": 83,
            "Base": 63,
            "Port": "",
            "Current Price": 4800.0,
            "Upside": "2.3x",
            "Position Type": "",
            "Artifact Updated": "Jun 16 (TF content 7.3x)",
            "SuperCycle": "AI",
            "FY2027": 8500,
            "FY2028": 11100,
            "FY2029": 14200,
            "FY2030": 17500,
            "Entry": 58,
            "Total": 61
        },
        {
            "Rank": 25,
            "Ticker": "AVGO",
            "Name": "Broadcom Inc",
            "EV Upside": 65,
            "Base": 80,
            "Port": "",
            "Current Price": 365.02,
            "Upside": "1.8x",
            "Position Type": "🔒 CHOKEPOINT\nDuopoly: Custom AI ASIC — only AVGO + MRVL design hyperscaler AI chips. Google TPU, Meta, Anthropic, OpenAI. Bell Labs InP fab. $73B AI backlog. 2026-2035+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, CPO, 800G, 1.6T",
            "FY2027": "549",
            "FY2028": "660",
            "FY2029": "735",
            "FY2030": "799",
            "Entry": 38,
            "Total": 63
        },
        {
            "Rank": 26,
            "Ticker": "2337.TW",
            "Name": "Macronix (旺宏)",
            "EV Upside": 66,
            "Base": 78,
            "Port": "",
            "Current Price": 162.5,
            "Upside": "1.8x",
            "Position Type": "⚡ BOTTLENECK\nTemporary: Accidental NOR/eMMC monopoly — China replicates in 2-3yrs. Expiration date visible.",
            "Artifact Updated": "Jun 16 (TrendForce margin)",
            "SuperCycle": "AI",
            "FY2027": 213,
            "FY2028": 300,
            "FY2029": 359,
            "FY2030": 431,
            "Change %": "-1.84%",
            "Entry": 40,
            "Total": 63
        },
        {
            "Rank": 27,
            "Ticker": "NVDA",
            "Name": "NVIDIA Corporation",
            "EV Upside": 55,
            "Base": 82,
            "Port": "",
            "Current Price": 192.53,
            "Upside": "1.7x",
            "Position Type": "",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, CPO, 800G, 1.6T",
            "FY2027": "242",
            "FY2028": "322",
            "FY2029": "411",
            "FY2030": "498",
            "Entry": 30,
            "Total": 61
        },
        {
            "Rank": 28,
            "Ticker": "COHR",
            "Name": "Coherent Corp",
            "EV Upside": 57,
            "Base": 80,
            "Port": "",
            "Current Price": 380.56,
            "Upside": "1.7x",
            "Position Type": "🔒 CHOKEPOINT\nVertical: Most advanced InP lines globally — doubling capacity TWICE still not enough. 2026-2030+",
            "Artifact Updated": "Jun 11 (restructure) +Jun12 InP fold +Nov10",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": "419",
            "FY2028": "653",
            "FY2029": "959",
            "FY2030": "1,242",
            "Change %": "-6.20%",
            "Entry": 32,
            "Total": 61
        },
        {
            "Rank": 29,
            "Ticker": "AVEX",
            "Name": "AEVEX Aerospace",
            "EV Upside": 78,
            "Base": 52,
            "Port": "",
            "Current Price": 17.2,
            "Upside": "2.5x",
            "Position Type": "⚡ BOTTLENECK\nTemporal: ForgeX first-mover in frontline mfg. Combat-proven. $645.7M sole-sourced. Replicable in 2-3yrs. PE 79% control. 3-5yr window.",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "26",
            "FY2028": "43",
            "FY2029": "68",
            "FY2030": "107",
            "Change %": "+5.87%",
            "Entry": 62,
            "Total": 56
        },
        {
            "Rank": 30,
            "Ticker": "6830.TWO",
            "Name": "MSScorps (汎銓科技)",
            "EV Upside": 35,
            "Base": 83,
            "Port": "",
            "Current Price": 564.0,
            "Upside": "1.4x",
            "Position Type": "🔒 CHOKEPOINT\nCPO PIC light leakage inspection. Patented in TW/JP/US. Suing Enli, refusing to license. 6yr co-development with customers. VICR-pattern dual moat (physics + legal).",
            "Artifact Updated": "Jun 9 (rebuild)",
            "SuperCycle": "AI, CPO",
            "FY2027": "170",
            "FY2028": "804",
            "FY2029": "2,405",
            "FY2030": "4,943",
            "Change %": "+0.55%",
            "Entry": 14,
            "Total": 55
        },
        {
            "Rank": 31,
            "Ticker": "002371.SZ",
            "Name": "北方华创 NAURA",
            "EV Upside": 36,
            "Base": 82,
            "Port": "",
            "Current Price": 459.0,
            "Upside": "1.4x",
            "Position Type": "China #1 WFE | CXMT capex",
            "Artifact Updated": "Jun 27",
            "SuperCycle": "Equipment, 国产替代",
            "FY2027": 435,
            "FY2028": 658,
            "FY2029": 811,
            "FY2030": 918,
            "Entry": 15,
            "Total": 55
        },
        {
            "Rank": 32,
            "Ticker": "4977.TW",
            "Name": "PCL Technologies (眾達-KY)",
            "EV Upside": 39,
            "Base": 76,
            "Port": "",
            "Current Price": 184.5,
            "Upside": "1.5x",
            "Position Type": "⚡ Bottleneck",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, CPO, 1.6T",
            "FY2027": "111",
            "FY2028": "278",
            "FY2029": "596",
            "FY2030": "1,026",
            "Change %": "-7.73%",
            "Entry": 19,
            "Total": 53
        },
        {
            "Rank": 33,
            "Ticker": "AIXA.DE",
            "Name": "Aixtron SE",
            "EV Upside": 34,
            "Base": 80,
            "Port": "",
            "Current Price": 52.12,
            "Upside": "1.4x",
            "Position Type": "🔒 CHOKEPOINT\nPhysics: 70-90% MOCVD share — tool of record for InP epi. Universal primitive for compound semi. 2026-2035+",
            "Artifact Updated": "Jun 16 (V1 lift + 25x)",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": 48,
            "FY2028": 74,
            "FY2029": 105,
            "FY2030": 134,
            "Change %": "-2.63%",
            "Entry": 14,
            "Total": 54
        },
        {
            "Rank": 34,
            "Ticker": "HPS-A.TO",
            "Name": "Hammond Power Solutions",
            "EV Upside": 38,
            "Base": 73,
            "Port": "",
            "Current Price": 324.67,
            "Upside": "1.5x",
            "Position Type": "⚡ BOTTLENECK\nDemand: DPA demand floor for transformers. #1 NA but competitive market. 2-3yr window.",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI",
            "FY2027": "C411",
            "FY2028": "C493",
            "FY2029": "C569",
            "FY2030": "C641",
            "Change %": "-2.41%",
            "Entry": 20,
            "Total": 52
        },
        {
            "Rank": 35,
            "Ticker": "EOS.AX",
            "Name": "Electro Optic Systems",
            "EV Upside": 34,
            "Base": 78,
            "Port": "",
            "Current Price": 9.44,
            "Upside": "1.4x",
            "Position Type": "🔒 CHOKEPOINT\nPhysics: Speed-of-light directed energy + ITAR-free. Zero marginal cost/shot. 2026-2035+",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "Other",
            "FY2027": 4.7,
            "FY2028": 13.5,
            "FY2029": 23.4,
            "FY2030": 30.5,
            "Change %": "+4.13%",
            "Entry": 14,
            "Total": 52
        },
        {
            "Rank": 36,
            "Ticker": "JBL",
            "Name": "Jabil Inc",
            "EV Upside": 31,
            "Base": 68,
            "Port": "",
            "Current Price": 358.6,
            "Upside": "1.5x",
            "Position Type": "📊 BENEFICIARY | Rule 10 capped EMS",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI",
            "FY2027": 395,
            "FY2028": 522,
            "FY2029": 653,
            "FY2030": 791,
            "Entry": 16,
            "Total": 47
        },
        {
            "Rank": 37,
            "Ticker": "603986.SH",
            "Name": "GigaDevice 兆易创新",
            "EV Upside": 14,
            "Base": 82,
            "Port": "",
            "Current Price": 770.0,
            "Upside": "1.2x",
            "Position Type": "BENEFICIARY | niche DRAM + MCU",
            "Artifact Updated": "Jun 25",
            "SuperCycle": "Memory, China, edge AI",
            "FY2027": 480,
            "FY2028": 898,
            "FY2029": 1134,
            "FY2030": 1319,
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 38,
            "Ticker": "002409.SZ",
            "Name": "雅克科技 Yoke Technology",
            "EV Upside": 12,
            "Base": 82,
            "Port": "",
            "Current Price": 188.6,
            "Upside": "1.2x",
            "Position Type": "⚡ BOTTLENECK\nHBM precursor oligopoly + memory-materials annuity",
            "Artifact Updated": "Jun 27 (demand-side capex-to-materials model, BOC Securities segments)",
            "SuperCycle": "AI, HBM, Memory, 国产替代",
            "FY2027": 157,
            "FY2028": 217,
            "FY2029": 284,
            "FY2030": 346,
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 39,
            "Ticker": "TSEM",
            "Name": "Tower Semiconductor",
            "EV Upside": 12,
            "Base": 82,
            "Port": "",
            "Current Price": 249.91,
            "Upside": "1.1x",
            "Position Type": "🔒 CHOKEPOINT\nCapital+Qual: ~85% SiPh foundry — 12-18mo requalification barrier. 2026-2030+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, CPO, 1.6T",
            "FY2027": "165",
            "FY2028": "285",
            "FY2029": "411",
            "FY2030": "528",
            "Change %": "-7.86%",
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 40,
            "Ticker": "CRDO",
            "Name": "Credo Technology",
            "EV Upside": 17,
            "Base": 75,
            "Port": "",
            "Current Price": 238.0,
            "Upside": "1.2x",
            "Position Type": "🔒 CHOKEPOINT\nIP: SerDes IP + ZeroFlap AEC — 100x reliability = must-have for training. Multi-sector. 2026-2032+",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI, 1.6T, 800G",
            "FY2027": 151,
            "FY2028": 291,
            "FY2029": 448,
            "FY2030": 599,
            "Change %": "-8.79%",
            "Entry": 1,
            "Total": 45
        },
        {
            "Rank": 41,
            "Ticker": "BESI.AS",
            "Name": "BE Semiconductor Industries",
            "EV Upside": 11,
            "Base": 73,
            "Port": "",
            "Current Price": 252.02,
            "Upside": "1.2x",
            "Position Type": "🔒 CHOKEPOINT | Hybrid bonding near-monopoly",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI, CPO",
            "FY2027": 192,
            "FY2028": 290,
            "FY2029": 358,
            "FY2030": 411,
            "Change %": "-2.25%",
            "Entry": 0,
            "Total": 44
        },
        {
            "Rank": 42,
            "Ticker": "BE",
            "Name": "Bloom Energy",
            "EV Upside": 16,
            "Base": 70,
            "Port": "",
            "Current Price": 252.02,
            "Upside": "1.2x",
            "Position Type": "⚡ BOTTLENECK\nSpeed: 90-day SOFC deployment advantage — fades as grid connections improve. 2-4yr window.",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI",
            "FY2027": "166",
            "FY2028": "311",
            "FY2029": "476",
            "FY2030": "602",
            "Change %": "-5.80%",
            "Entry": 2,
            "Total": 43
        },
        {
            "Rank": 43,
            "Ticker": "000725.SZ",
            "Name": "京东方A BOE Technology",
            "EV Upside": 23,
            "Base": 65,
            "Port": "",
            "Current Price": 7.79,
            "Upside": "1.3x",
            "Position Type": "📊 BENEFICIARY\nDisplay platform + glass-core substrate optionality",
            "Artifact Updated": "Jun 27 (new dive, glass-core substrate cross-read to LPKF/GLW)",
            "SuperCycle": "Display, OLED, Glass Substrate",
            "FY2027": 7.24,
            "FY2028": 10.5,
            "FY2029": 14.6,
            "FY2030": 18.1,
            "Entry": 9,
            "Total": 43
        },
        {
            "Rank": 44,
            "Ticker": "PNG.V",
            "Name": "Kraken Robotics",
            "EV Upside": 17,
            "Base": 75,
            "Port": "",
            "Current Price": 6.54,
            "Upside": "1.2x",
            "Position Type": "🔒 CHOKEPOINT\nQualification: Sonardyne gold standard underwater positioning — decades of qual inertia. 2026-2032+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "-",
            "FY2028": "C8.03",
            "FY2029": "C11.03",
            "FY2030": "C14.87",
            "Change %": "-2.02%",
            "Entry": 2,
            "Total": 46
        },
        {
            "Rank": 45,
            "Ticker": "AMD",
            "Name": "Advanced Micro Devices",
            "EV Upside": 2,
            "Base": 78,
            "Port": "",
            "Current Price": 521.58,
            "Upside": "1.0x",
            "Position Type": "📊 BENEFICIARY (system layer)",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI, CPO",
            "FY2027": 312,
            "FY2028": 536,
            "FY2029": 782,
            "FY2030": 992,
            "Entry": 0,
            "Total": 47
        },
        {
            "Rank": 46,
            "Ticker": "600584.SH",
            "Name": "长电科技 JCET Group",
            "EV Upside": -4,
            "Base": 75,
            "Port": "",
            "Current Price": 100.89,
            "Upside": "1.0x",
            "Position Type": "📊 BENEFICIARY\nChina advanced-packaging platform, not global chokepoint",
            "Artifact Updated": "Jun 27 (new dive, application-mix model)",
            "SuperCycle": "AI, Adv Pkg, Memory, 国産替代",
            "FY2027": 58,
            "FY2028": 96,
            "FY2029": 144,
            "FY2030": 199,
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 47,
            "Ticker": "NRGV",
            "Name": "Energy Vault Holdings",
            "EV Upside": 16,
            "Base": 57,
            "Port": "",
            "Current Price": 4.21,
            "Upside": "1.3x",
            "Position Type": "⚡ BOTTLENECK\nCapacity: BESS deployer — no moat, competitive. Asset Vault recurring model unproven. 2-3yr window.",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "1.79",
            "FY2028": "5.42",
            "FY2029": "10.50",
            "FY2030": "16.28",
            "Change %": "-9.54%",
            "Entry": 5,
            "Total": 36
        },
        {
            "Rank": 48,
            "Ticker": "VICR",
            "Name": "Vicor Corporation",
            "EV Upside": -8,
            "Base": 82,
            "Port": "",
            "Current Price": 326.93,
            "Upside": "0.9x",
            "Position Type": "🔒 CHOKEPOINT\nPhysics+Legal: VPD required underneath CPO + ITC import ban for life of patents. 2026-2035+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI",
            "FY2027": "159",
            "FY2028": "296",
            "FY2029": "480",
            "FY2030": "647",
            "Change %": "-9.51%",
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 49,
            "Ticker": "ACMR",
            "Name": "ACM Research",
            "EV Upside": -6,
            "Base": 78,
            "Port": "",
            "Current Price": 116.34,
            "Upside": "0.9x",
            "Position Type": "⚡ BOTTLENECK\nChina WFE: wet-clean + ECP + adv pkg + glass substrate",
            "Artifact Updated": "Jun 27 (new dive, China WFE localization + panel-level ECP)",
            "SuperCycle": "AI, WFE, 国産替代, Glass Substrate",
            "FY2027": 68,
            "FY2028": 107,
            "FY2029": 149,
            "FY2030": 183,
            "Entry": 0,
            "Total": 47
        },
        {
            "Rank": 50,
            "Ticker": "STM",
            "Name": "STMicroelectronics",
            "EV Upside": 2,
            "Base": 65,
            "Port": "",
            "Current Price": 71.42,
            "Upside": "1.0x",
            "Position Type": "Rule 10 capped IDM. SiC #1 (32.6%), GaN, MEMS, STM32 MCU. Data center $1B→$2B. No segment passes Rule 6. Ecosystem beta across 800V/robotics/satellite/edge AI.",
            "Artifact Updated": "Jun 15 (new dive)",
            "SuperCycle": "Other",
            "FY2027": 54,
            "FY2028": 74,
            "FY2029": 97,
            "FY2030": 118,
            "Entry": 0,
            "Total": 39
        },
        {
            "Rank": 51,
            "Ticker": "INTC",
            "Name": "Intel Corporation",
            "EV Upside": -13,
            "Base": 80,
            "Port": "",
            "Current Price": 128.32,
            "Upside": "0.8x",
            "Position Type": "",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI, CPO",
            "FY2027": 57,
            "FY2028": 108,
            "FY2029": 164,
            "FY2030": 226,
            "Entry": 0,
            "Total": 48
        },
        {
            "Rank": 52,
            "Ticker": "300223.SZ",
            "Name": "北京君正 Ingenic",
            "EV Upside": -25,
            "Base": 83,
            "Port": "",
            "Current Price": 233.21,
            "Upside": "0.7x",
            "Position Type": "Car-grade SRAM #1 + niche DRAM",
            "Artifact Updated": "Jun 25",
            "SuperCycle": "Memory, Auto, AI Edge",
            "FY2027": 143,
            "FY2028": 164,
            "FY2029": 179,
            "FY2030": 195,
            "Entry": 0,
            "Total": 50
        },
        {
            "Rank": 53,
            "Ticker": "300666.SZ",
            "Name": "江丰电子 Konfoong Materials",
            "EV Upside": -26,
            "Base": 78,
            "Port": "",
            "Current Price": 354.78,
            "Upside": "0.7x",
            "Position Type": "⚡ BOTTLENECK\nPVD target oligopoly + ESC second curve",
            "Artifact Updated": "Jun 27 (rebuilt: 276M shares, ¥355, ESC 65% GM, FY28 ¥236)",
            "SuperCycle": "AI, Memory, 国産替代, ESC",
            "FY2027": 136,
            "FY2028": 236,
            "FY2029": 350,
            "FY2030": 460,
            "Entry": 0,
            "Total": 47
        },
        {
            "Rank": 54,
            "Ticker": "688409.SH",
            "Name": "富创精密 Fortune Precision",
            "EV Upside": -22,
            "Base": 75,
            "Port": "",
            "Current Price": 298.0,
            "Upside": "0.7x",
            "Position Type": "📊 BENEFICIARY\nChina WFE precision parts + gas-delivery subsystems",
            "Artifact Updated": "Jun 27 (new dive, WFE subsystem/parts layer)",
            "SuperCycle": "AI, WFE Subsystems, 国産替代",
            "FY2027": 94,
            "FY2028": 211,
            "FY2029": 362,
            "FY2030": 523,
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 55,
            "Ticker": "SMTC",
            "Name": "Semtech Corporation",
            "EV Upside": -19,
            "Base": 72,
            "Port": "",
            "Current Price": 149.75,
            "Upside": "0.7x",
            "Position Type": "⚡ BOTTLENECK-ADJACENT | 224G optical ICs",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI, CPO, 800G, 1.6T",
            "FY2027": 65,
            "FY2028": 111,
            "FY2029": 160,
            "FY2030": 208,
            "Entry": 0,
            "Total": 43
        },
        {
            "Rank": 56,
            "Ticker": "MRVL",
            "Name": "Marvell Technology",
            "EV Upside": -30,
            "Base": 82,
            "Port": "",
            "Current Price": 252.04,
            "Upside": "0.6x",
            "Position Type": "🔒 CHOKEPOINT\nDuopoly: Custom ASIC — only MRVL + Broadcom design hyperscaler AI chips. 2-3yr design cycle = lock-in. Amazon, Google, Microsoft, Meta. 2026-2035+",
            "Artifact Updated": "Jun 27 (v4.2: 30x→20x, Base 78→82%, CXL/TPU vectors)",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": 88,
            "FY2028": 159,
            "FY2029": 248,
            "FY2030": 347,
            "Change %": "-3.18%",
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 57,
            "Ticker": "688008.SH",
            "Name": "澜起科技 Montage Technology",
            "EV Upside": -31,
            "Base": 82,
            "Port": "",
            "Current Price": 296.06,
            "Upside": "0.6x",
            "Position Type": "⚡ BOTTLENECK\nChina memory-interface / CXL / PCIe interconnect platform",
            "Artifact Updated": "Jun 27 (new dive, China MRVL/ALAB analogue for memory-wall)",
            "SuperCycle": "AI, CXL, Memory Interface, 国産替代",
            "FY2027": 110,
            "FY2028": 185,
            "FY2029": 261,
            "FY2030": 327,
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 58,
            "Ticker": "002484.SZ",
            "Name": "江海股份 Jianghai Capacitor",
            "EV Upside": -23,
            "Base": 68,
            "Port": "",
            "Current Price": 104.82,
            "Upside": "0.7x",
            "Position Type": "📊 BENEFICIARY\nAI rack power capacitor platform",
            "Artifact Updated": "Jun 27 (new dive, AI power-density + supercap optionality)",
            "SuperCycle": "AI Power, Passive Components",
            "FY2027": 46,
            "FY2028": 69,
            "FY2029": 91,
            "FY2030": 110,
            "Entry": 0,
            "Total": 41
        },
        {
            "Rank": 59,
            "Ticker": "688072.SH",
            "Name": "拓荆科技 Piotech",
            "EV Upside": -29,
            "Base": 80,
            "Port": "",
            "Current Price": 832.0,
            "Upside": "0.6x",
            "Position Type": "⚡ BOTTLENECK\nChina thin-film deposition + hybrid bonding WFE",
            "Artifact Updated": "Jun 27 (new dive, AMEC deposition pair + hybrid bonding)",
            "SuperCycle": "AI, WFE, CVD/ALD, 国産替代",
            "FY2027": 264,
            "FY2028": 529,
            "FY2029": 870,
            "FY2030": 1332,
            "Entry": 0,
            "Total": 48
        },
        {
            "Rank": 60,
            "Ticker": "300408.SZ",
            "Name": "Three-Circle Group",
            "EV Upside": -28,
            "Base": 78,
            "Port": "",
            "Current Price": 160.05,
            "Upside": "0.6x",
            "Position Type": "⚡/🔒 MIXED\nFiber optic ceramic ferrule 70-80% global monopoly (85%+ MPO/MT). MLCC fastest-growing Chinese w/ 100% powder self-supply. Dual AI thesis. H-share HKEX listing pending",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI, CPO",
            "FY2027": 75,
            "FY2028": 103,
            "FY2029": 127,
            "FY2030": 160,
            "Entry": 0,
            "Total": 47
        },
        {
            "Rank": 61,
            "Ticker": "688120.SH",
            "Name": "华海清科 Hwatsing",
            "EV Upside": -28,
            "Base": 78,
            "Port": "",
            "Current Price": 316.32,
            "Upside": "0.6x",
            "Position Type": "⚡ BOTTLENECK\nChina CMP + panel-level CMP + HBM/glass substrate",
            "Artifact Updated": "Jun 27 (new dive, CMP champion + panel-level glass substrate)",
            "SuperCycle": "AI, WFE, CMP, 国産替代",
            "FY2027": 113,
            "FY2028": 204,
            "FY2029": 333,
            "FY2030": 461,
            "Entry": 0,
            "Total": 47
        },
        {
            "Rank": 62,
            "Ticker": "GLW",
            "Name": "Corning",
            "EV Upside": -16,
            "Base": 65,
            "Port": "",
            "Current Price": 221.05,
            "Upside": "0.7x",
            "Position Type": "RULE 10 | Glass science + AI optical",
            "Artifact Updated": "Jun 25",
            "SuperCycle": "Photonics, Glass, CPO",
            "FY2027": 126,
            "FY2028": 165,
            "FY2029": 209,
            "FY2030": 257,
            "Entry": 0,
            "Total": 39
        },
        {
            "Rank": 63,
            "Ticker": "300285.SZ",
            "Name": "Sinocera (国瓷材料)",
            "EV Upside": -30,
            "Base": 75,
            "Port": "",
            "Current Price": 102.81,
            "Upside": "0.6x",
            "Position Type": "",
            "Artifact Updated": "Jun 16 (TF content 7.3x)",
            "SuperCycle": "AI",
            "FY2027": 34,
            "FY2028": 62,
            "FY2029": 78,
            "FY2030": 96,
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 64,
            "Ticker": "SHMD",
            "Name": "SCHMID Group",
            "EV Upside": -9,
            "Base": 53,
            "Port": "",
            "Current Price": 5.72,
            "Upside": "0.8x",
            "Position Type": "❌ FAIL band\nGlass-line equipment integrator — owns the LINE not the CHEMISTRY (Atotech/MKS). Delisting proceeding + negative GM + active dilution. Pre-registered upgrade path: 20-F clear / named glass order / CpK 1.33 gate",
            "Artifact Updated": "Jun 12 (new dive)",
            "SuperCycle": "AI, CPO",
            "FY2027": 1.78,
            "FY2028": 4.7,
            "FY2029": 7.13,
            "FY2030": 9.11,
            "Entry": 0,
            "Total": 32
        },
        {
            "Rank": 65,
            "Ticker": "688012.SH",
            "Name": "中微公司 AMEC",
            "EV Upside": -40,
            "Base": 82,
            "Port": "",
            "Current Price": 456.69,
            "Upside": "0.5x",
            "Position Type": "⚡ BOTTLENECK\nChina high-end etch + deposition WFE platform",
            "Artifact Updated": "Jun 27 (new dive, China etch champion + thin-film expansion)",
            "SuperCycle": "AI, WFE, Etch, 国産替代",
            "FY2027": 135,
            "FY2028": 234,
            "FY2029": 354,
            "FY2030": 493,
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 66,
            "Ticker": "002428.SZ",
            "Name": "云南锗业 Yunnan Germanium (InP)",
            "EV Upside": -34,
            "Base": 72,
            "Port": "",
            "Current Price": 120.48,
            "Upside": "0.5x",
            "Position Type": "🔒 CHOKEPOINT | Domestic InP monopoly | Near-zero EV",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI, CPO, 800G, 1.6T",
            "FY2027": 34,
            "FY2028": 64,
            "FY2029": 100,
            "FY2030": 127,
            "Entry": 0,
            "Total": 43
        },
        {
            "Rank": 67,
            "Ticker": "1888.HK",
            "Name": "建滔積層板 Kingboard Laminates",
            "EV Upside": -35,
            "Base": 65,
            "Port": "",
            "Current Price": 98.55,
            "Upside": "0.5x",
            "Position Type": "⚡ BOTTLENECK | Cyclical CCL pricing | NEG EV",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI",
            "FY2027": 33,
            "FY2028": 46,
            "FY2029": 42,
            "FY2030": 36,
            "Change %": "+2.48%",
            "Entry": 0,
            "Total": 39
        },
        {
            "Rank": 68,
            "Ticker": "ALAB",
            "Name": "Astera Labs",
            "EV Upside": -45,
            "Base": 75,
            "Port": "",
            "Current Price": 391.74,
            "Upside": "0.4x",
            "Position Type": "⚡ BOTTLENECK\nTemporal: PCIe Gen 6 first-mover. 80% AI server penetration. Standards-based = competitors catching up. Amazon $6.5B warrant. 2-3yr window.",
            "Artifact Updated": "Jun 27 (v4.2 audit: 25x→20x, FY28 $195→$156)",
            "SuperCycle": "AI, 1.6T, 800G",
            "FY2027": 100,
            "FY2028": 156,
            "FY2029": 217,
            "FY2030": 278,
            "Change %": "-6.70%",
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 69,
            "Ticker": "ARM",
            "Name": "Arm Holdings",
            "EV Upside": -46,
            "Base": 75,
            "Port": "",
            "Current Price": 334.27,
            "Upside": "0.4x",
            "Position Type": "🔒 CHOKEPOINT\nISA monopoly — the world's software compiles to Arm. 50% hyperscaler CPU, ~100% DPU/SmartNIC. AGI CPU merchant ramp. RISC-V = the falsification test",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI",
            "FY2027": 85,
            "FY2028": 128,
            "FY2029": 192,
            "FY2030": 275,
            "Change %": "+0.82%",
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 70,
            "Ticker": "002384.SZ",
            "Name": "东山精密 Dongshan Precision",
            "EV Upside": -41,
            "Base": 67,
            "Port": "",
            "Current Price": 260.32,
            "Upside": "0.4x",
            "Position Type": "📊 BENEFICIARY | Rule 10 capped + China -3 | NEG EV",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI, 800G, 1.6T",
            "FY2027": 61,
            "FY2028": 100,
            "FY2029": 145,
            "FY2030": 190,
            "Entry": 0,
            "Total": 40
        },
        {
            "Rank": 71,
            "Ticker": "OUST",
            "Name": "Ouster Inc",
            "EV Upside": -49,
            "Base": 75,
            "Port": "",
            "Current Price": 42.02,
            "Upside": "0.3x",
            "Position Type": "⚡ BOTTLENECK\nPhysical AI perception platform (was 🔒, downgraded Rule 6)",
            "Artifact Updated": "Jun 27 (v4.2 audit: shares 180M→72M, 30x→20x, Base 82→75%)",
            "SuperCycle": "Other",
            "FY2027": 0,
            "FY2028": 14.6,
            "FY2029": 44.7,
            "FY2030": 86.5,
            "Change %": "-16.41%",
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 72,
            "Ticker": "PL",
            "Name": "Planet Labs",
            "EV Upside": -49,
            "Base": 67,
            "Port": "",
            "Current Price": 27.07,
            "Upside": "0.3x",
            "Position Type": "⚡ BOTTLENECK\nRegulatory: Unclassified intelligence niche — valid moat but satellite fleet depreciates. 2-3yr window.",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "0.78",
            "FY2028": "7.10",
            "FY2029": "17.28",
            "FY2030": "34.35",
            "Change %": "-1.36%",
            "Entry": 0,
            "Total": 40
        },
        {
            "Rank": 73,
            "Ticker": "WOLF",
            "Name": "Wolfspeed",
            "EV Upside": -39,
            "Base": 55,
            "Port": "",
            "Current Price": 45.97,
            "Upside": "0.3x",
            "Position Type": "",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "neg",
            "FY2028": "13",
            "FY2029": "59",
            "FY2030": "114",
            "Entry": 0,
            "Total": 33
        },
        {
            "Rank": 74,
            "Ticker": "600330.SH",
            "Name": "天通股份 Tiantong (LN/TFLN)",
            "EV Upside": -44,
            "Base": 57,
            "Port": "",
            "Current Price": 32.75,
            "Upside": "0.2x",
            "Position Type": "❌ FAIL | Governance + pre-revenue + Rule 10",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI, CPO, 1.6T",
            "FY2027": 2.2,
            "FY2028": 7.3,
            "FY2029": 13.2,
            "FY2030": 18.7,
            "Entry": 0,
            "Total": 34
        }
    ],
    "zh-CN": [
        {
            "Rank": 1,
            "Ticker": "SIVE.ST",
            "Name": "西弗斯半导体公司",
            "EV Upside": 438,
            "Base": 92,
            "Port": "✓",
            "Current Price": 63.35,
            "Upside": "5.8x",
            "Position Type": "🔒 阻塞点\n物理：连续激光——硅不能发光。每个 CPO 一代。 2026-2035+",
            "Artifact Updated": "Jun 15 (305M verified, V11 AMD, no pre-dilution)",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": 126,
            "FY2028": 365,
            "FY2029": 598,
            "FY2030": 810,
            "Change %": "-13.64%",
            "Entry": 118,
            "Total": 102
        },
        {
            "Rank": 2,
            "Ticker": "3363.TWO",
            "Name": "FOCI (上转)",
            "EV Upside": 410,
            "Base": 81,
            "Port": "✓",
            "Current Price": 575.0,
            "Upside": "6.1x",
            "Position Type": "⚡ 瓶颈",
            "Artifact Updated": "Jun 10 (scrub)",
            "SuperCycle": "AI, CPO",
            "FY2027": "1,307",
            "FY2028": "3,484",
            "FY2029": "5,728",
            "FY2030": "7,963",
            "Change %": "-4.40%",
            "Entry": 121,
            "Total": 97
        },
        {
            "Rank": 3,
            "Ticker": "LPK.DE",
            "Name": "LPKF 激光与电子",
            "EV Upside": 409,
            "Base": 83,
            "Port": "✓",
            "Current Price": 21.1,
            "Upside": "5.9x",
            "Position Type": "🔒 阻塞点\n物理：LIDE 玻璃 TGV — 有机玻璃无法支持下一代。三重超级循环：DB5 AI包装+DB3 LEO Space（SpaceX）+DB8 Defense。 2027-2035+",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI, CPO",
            "FY2027": 54,
            "FY2028": 125,
            "FY2029": 243,
            "FY2030": 386,
            "Change %": "-1.80%",
            "Entry": 119,
            "Total": 97
        },
        {
            "Rank": 4,
            "Ticker": "005930.KS",
            "Name": "三星电子",
            "EV Upside": 325,
            "Base": 90,
            "Port": "✓",
            "Current Price": 339000.0,
            "Upside": "4.6x",
            "Position Type": "🔒 阻塞点\n建筑：中国唯一的非美国代工厂+存储器。三星=默认的中国人工智能合作伙伴。 2026-2030+",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI",
            "FY2027": 1289000,
            "FY2028": 1563000,
            "FY2029": 1754000,
            "FY2030": 1889000,
            "Change %": "+3.88%",
            "Entry": 106,
            "Total": 96
        },
        {
            "Rank": 5,
            "Ticker": "8147.TWO",
            "Name": "明思电子工程",
            "EV Upside": 325,
            "Base": 70,
            "Port": "",
            "Current Price": 137.0,
            "Upside": "5.6x",
            "Position Type": "⚡ 瓶颈",
            "Artifact Updated": "Jun 10 (restructure)",
            "SuperCycle": "AI, CPO",
            "FY2027": "234",
            "FY2028": "774",
            "FY2029": "1,709",
            "FY2030": "2,703",
            "Change %": "+0.79%",
            "Entry": 100,
            "Total": 82
        },
        {
            "Rank": 6,
            "Ticker": "000660.KS",
            "Name": "SK海力士",
            "EV Upside": 255,
            "Base": 93,
            "Port": "✓",
            "Current Price": 2670000.0,
            "Upside": "3.7x",
            "Position Type": "🔒 阻塞点\n架构：#1 HBM — 4nm 逻辑基芯片引线加宽了每一代。内存架构永久。 2026-2030+",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI",
            "FY2027": 8322000,
            "FY2028": 9986000,
            "FY2029": 11654000,
            "FY2030": 12899000,
            "Change %": "+1.15%",
            "Entry": 94,
            "Total": 93
        },
        {
            "Rank": 7,
            "Ticker": "ALRIB",
            "Name": "Riber SA（MBE设备）",
            "EV Upside": 240,
            "Base": 70,
            "Port": "",
            "Current Price": 11.3,
            "Upside": "4.4x",
            "Position Type": "🔒 阻塞点\n物理：用于QD激光器的MBE设备+ROSIE SiPh+量子材料。 2027-2035+",
            "Artifact Updated": "Jun 10 (restructure)",
            "SuperCycle": "AI, CPO",
            "FY2027": "33",
            "FY2028": "50",
            "FY2029": "72",
            "FY2030": "106",
            "Change %": "-3.42%",
            "Entry": 100,
            "Total": 82
        },
        {
            "Rank": 8,
            "Ticker": "XFAB",
            "Name": "X-Fab 硅铸造厂",
            "EV Upside": 233,
            "Base": 77,
            "Port": "",
            "Current Price": 8.0,
            "Upside": "4.0x",
            "Position Type": "WL",
            "Artifact Updated": "Jun 10 (restructure)",
            "SuperCycle": "AI, CPO, 800G",
            "FY2027": "18.47",
            "FY2028": "32.21",
            "FY2029": "50.69",
            "FY2030": "71.45",
            "Entry": 100,
            "Total": 86
        },
        {
            "Rank": 9,
            "Ticker": "MU",
            "Name": "美光科技",
            "EV Upside": 216,
            "Base": 88,
            "Port": "✓",
            "Current Price": 1132.33,
            "Upside": "3.5x",
            "Position Type": "⚡ 瓶颈\n供应：#3 HBM — 暂时的供需失衡。中国禁止限制TAM。 1-3年窗口期。",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI",
            "FY2027": 2842,
            "FY2028": 3908,
            "FY2029": 4855,
            "FY2030": 5684,
            "Change %": "-2.99%",
            "Entry": 86,
            "Total": 87
        },
        {
            "Rank": 10,
            "Ticker": "AAOI",
            "Name": "应用光电",
            "EV Upside": 218,
            "Base": 74,
            "Port": "✓",
            "Current Price": 135.69,
            "Upside": "4.0x",
            "Position Type": "⚡ 瓶颈\n产能：收发器组装——产能扩大至500K/月。竞争市场。 1-2年窗口期。",
            "Artifact Updated": "Jun 10 (restructure) +Jun13 ATM/share fix +Jun13 VI correction +AXT/Nov10",
            "SuperCycle": "AI, 1.6T, 800G",
            "FY2027": "272",
            "FY2028": "536",
            "FY2029": "671",
            "FY2030": "581",
            "Change %": "-11.85%",
            "Entry": 99,
            "Total": 84
        },
        {
            "Rank": 11,
            "Ticker": "NBIS",
            "Name": "尼比斯集团",
            "EV Upside": 192,
            "Base": 83,
            "Port": "",
            "Current Price": 240.3,
            "Upside": "3.3x",
            "Position Type": "⚡ 瓶颈",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI",
            "FY2027": 291,
            "FY2028": 795,
            "FY2029": 1252,
            "FY2030": 1685,
            "Change %": "-9.42%",
            "Entry": 83,
            "Total": 83
        },
        {
            "Rank": 12,
            "Ticker": "IQE.L",
            "Name": "IQE公司",
            "EV Upside": 185,
            "Base": 77,
            "Port": "",
            "Current Price": 46.8,
            "Upside": "3.4x",
            "Position Type": "⚡ 瓶颈\n催化剂：并购战略审查——事件驱动，而非结构性。单触发。 6-12个月窗口。",
            "Artifact Updated": "Jun 15 (InP+TSEM+margin)",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": 77,
            "FY2028": 159,
            "FY2029": 187,
            "FY2030": 205,
            "Change %": "-15.00%",
            "Entry": 85,
            "Total": 80
        },
        {
            "Rank": 13,
            "Ticker": "6451.TW",
            "Name": "顺欣科技",
            "EV Upside": 172,
            "Base": 82,
            "Port": "✓",
            "Current Price": 598.0,
            "Upside": "3.1x",
            "Position Type": "🔒 阻塞点\n建筑：CPO 封装 — 富士康光学引擎 FAU 对准。 2027-2032+",
            "Artifact Updated": "Jun 27 (v4.2: TSMC COUPE confirmed, Base 88→82%, decomposed margins)",
            "SuperCycle": "AI, CPO",
            "FY2027": 886,
            "FY2028": 1849,
            "FY2029": 2859,
            "FY2030": 3915,
            "Change %": "-9.88%",
            "Entry": 77,
            "Total": 80
        },
        {
            "Rank": 14,
            "Ticker": "AMPX",
            "Name": "安普瑞斯科技",
            "EV Upside": 169,
            "Base": 75,
            "Port": "",
            "Current Price": 12.91,
            "Upside": "3.3x",
            "Position Type": "🔒 阻塞点\n物理+监管：500 Wh/kg，2x 内无竞争对手 + NDAA 监管护城河。 2026-2035+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "21",
            "FY2028": "42",
            "FY2029": "68",
            "FY2030": "101",
            "Change %": "-7.83%",
            "Entry": 81,
            "Total": 77
        },
        {
            "Rank": 15,
            "Ticker": "SNDK",
            "Name": "闪迪公司",
            "EV Upside": 155,
            "Base": 87,
            "Port": "✓",
            "Current Price": 2090.71,
            "Upside": "2.8x",
            "Position Type": "⚡ 瓶颈\n供应：NAND 短缺——新晶圆厂即将建成（三星 P5、SK 海力士中国）。到 2027 年上半年。",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI",
            "FY2027": 4025,
            "FY2028": 5822,
            "FY2029": 7452,
            "FY2030": 8815,
            "Change %": "-4.75%",
            "Entry": 70,
            "Total": 80
        },
        {
            "Rank": 16,
            "Ticker": "SOI.PA",
            "Name": "索伊泰克公司",
            "EV Upside": 132,
            "Base": 87,
            "Port": "",
            "Current Price": 114.35,
            "Upside": "2.5x",
            "Position Type": "🔒 阻塞点\nIP：>95% 光子学-SOI、3,500 多项智能切割专利\nSiN = 补数（忽略）。可替代容量射频→光子学。",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": "148",
            "FY2028": "288",
            "FY2029": "653",
            "FY2030": "1,342",
            "Change %": "-6.31%",
            "Entry": 63,
            "Total": 77
        },
        {
            "Rank": 17,
            "Ticker": "AEHR",
            "Name": "空气测试系统",
            "EV Upside": 86,
            "Base": 93,
            "Port": "",
            "Current Price": 91.81,
            "Upside": "1.9x",
            "Position Type": "🔒 阻塞点\n物理：WLBI 唯一来源——不存在竞争对手。每个复合半。 2026-2035+",
            "Artifact Updated": "Jun 11 (restructure) +Nov10",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": "80",
            "FY2028": "177",
            "FY2029": "261",
            "FY2030": "321",
            "Change %": "-14.14%",
            "Entry": 45,
            "Total": 74
        },
        {
            "Rank": 18,
            "Ticker": "FTC.L",
            "Name": "菲尔创力PLC",
            "EV Upside": 86,
            "Base": 80,
            "Port": "",
            "Current Price": 230.0,
            "Upside": "2.1x",
            "Position Type": "🔒 阻塞点\n物理：E波段GaN SSPA垄断+V波段消费终端TAM（SpaceX资助研发）。产能锁定阻碍了亚马逊。金顶 #1 承包商链接。 2026-2035+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, Other",
            "FY2027": "213",
            "FY2028": "477",
            "FY2029": "864",
            "FY2030": "1,379",
            "Change %": "+1.48%",
            "Entry": 52,
            "Total": 69
        },
        {
            "Rank": 19,
            "Ticker": "LITE",
            "Name": "鲁门图姆控股",
            "EV Upside": 80,
            "Base": 82,
            "Port": "",
            "Current Price": 816.98,
            "Upside": "2.0x",
            "Position Type": "🔒 阻塞点\n物理学：EML 激光器近乎垄断——产能到 2029 年就已售罄。2026-2030+",
            "Artifact Updated": "Jun 11 (restructure) +Jun12 InP fold +Nov10",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": "980",
            "FY2028": "1,615",
            "FY2029": "2,241",
            "FY2030": "2,882",
            "Change %": "-8.61%",
            "Entry": 49,
            "Total": 69
        },
        {
            "Rank": 20,
            "Ticker": "3105.TW",
            "Name": "永胜半导体",
            "EV Upside": 84,
            "Base": 82,
            "Port": "",
            "Current Price": 424.0,
            "Upside": "2.0x",
            "Position Type": "⚡ 瓶颈",
            "Artifact Updated": "Jun 11 (restructure) +Nov10",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": "513",
            "FY2028": "858",
            "FY2029": "1,128",
            "FY2030": "1,369",
            "Change %": "-1.31%",
            "Entry": 51,
            "Total": 70
        },
        {
            "Rank": 21,
            "Ticker": "688596.SH",
            "Name": "正帆科技 Gentech",
            "EV Upside": 81,
            "Base": 73,
            "Port": "",
            "Current Price": 65.95,
            "Upside": "2.1x",
            "Position Type": "📊 受益人\n中国晶圆厂气体/化学品+WFE子系统+OPEX平台",
            "Artifact Updated": "Jun 27 (new dive, fab infrastructure + Gas Box + quartz/SiC + precursors)",
            "SuperCycle": "AI, WFE Subsystems, Gas/Chemical, 国産替代",
            "FY2027": 68,
            "FY2028": 139,
            "FY2029": 219,
            "FY2030": 293,
            "Entry": 53,
            "Total": 65
        },
        {
            "Rank": 22,
            "Ticker": "000636.SZ",
            "Name": "Fenghua Advanced (风华高科)",
            "EV Upside": 76,
            "Base": 80,
            "Port": "",
            "Current Price": 78.5,
            "Upside": "1.9x",
            "Position Type": "WL",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI",
            "FY2027": 81,
            "FY2028": 153,
            "FY2029": 191,
            "FY2030": 209,
            "Entry": 47,
            "Total": 67
        },
        {
            "Rank": 23,
            "Ticker": "BRUN",
            "Name": "加速跑",
            "EV Upside": 83,
            "Base": 68,
            "Port": "",
            "Current Price": 34.23,
            "Upside": "2.2x",
            "Position Type": "",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI",
            "FY2027": "39",
            "FY2028": "76",
            "FY2029": "112",
            "FY2030": "150",
            "Entry": 56,
            "Total": 63
        },
        {
            "Rank": 24,
            "Ticker": "4078.T",
            "Name": "堺化学",
            "EV Upside": 83,
            "Base": 63,
            "Port": "",
            "Current Price": 4800.0,
            "Upside": "2.3x",
            "Position Type": "",
            "Artifact Updated": "Jun 16 (TF content 7.3x)",
            "SuperCycle": "AI",
            "FY2027": 8500,
            "FY2028": 11100,
            "FY2029": 14200,
            "FY2030": 17500,
            "Entry": 58,
            "Total": 61
        },
        {
            "Rank": 25,
            "Ticker": "AVGO",
            "Name": "博通公司",
            "EV Upside": 65,
            "Base": 80,
            "Port": "",
            "Current Price": 365.02,
            "Upside": "1.8x",
            "Position Type": "🔒 阻塞点\n双寡头：定制 AI ASIC——只有 AVGO + MRVL 设计超大规模 AI 芯片。谷歌 TPU、Meta、Anthropic、OpenAI。贝尔实验室 InP 工厂。 $73B 人工智能积压。 2026-2035+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, CPO, 800G, 1.6T",
            "FY2027": "549",
            "FY2028": "660",
            "FY2029": "735",
            "FY2030": "799",
            "Entry": 38,
            "Total": 63
        },
        {
            "Rank": 26,
            "Ticker": "2337.TW",
            "Name": "Macronix (旺宏)",
            "EV Upside": 66,
            "Base": 78,
            "Port": "",
            "Current Price": 162.5,
            "Upside": "1.8x",
            "Position Type": "⚡ 瓶颈\n临时：意外的 NOR/eMMC 垄断——中国将在 2-3 年内复制。有效期可见。",
            "Artifact Updated": "Jun 16 (TrendForce margin)",
            "SuperCycle": "AI",
            "FY2027": 213,
            "FY2028": 300,
            "FY2029": 359,
            "FY2030": 431,
            "Change %": "-1.84%",
            "Entry": 40,
            "Total": 63
        },
        {
            "Rank": 27,
            "Ticker": "NVDA",
            "Name": "英伟达公司",
            "EV Upside": 55,
            "Base": 82,
            "Port": "",
            "Current Price": 192.53,
            "Upside": "1.7x",
            "Position Type": "",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, CPO, 800G, 1.6T",
            "FY2027": "242",
            "FY2028": "322",
            "FY2029": "411",
            "FY2030": "498",
            "Entry": 30,
            "Total": 61
        },
        {
            "Rank": 28,
            "Ticker": "COHR",
            "Name": "相干公司",
            "EV Upside": 57,
            "Base": 80,
            "Port": "",
            "Current Price": 380.56,
            "Upside": "1.7x",
            "Position Type": "🔒 阻塞点\n垂直：全球最先进的 InP 生产线——产能翻倍仍然不够。 2026-2030+",
            "Artifact Updated": "Jun 11 (restructure) +Jun12 InP fold +Nov10",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": "419",
            "FY2028": "653",
            "FY2029": "959",
            "FY2030": "1,242",
            "Change %": "-6.20%",
            "Entry": 32,
            "Total": 61
        },
        {
            "Rank": 29,
            "Ticker": "AVEX",
            "Name": "AEVEX 航空航天",
            "EV Upside": 78,
            "Base": 52,
            "Port": "",
            "Current Price": 17.2,
            "Upside": "2.5x",
            "Position Type": "⚡ 瓶颈\nTemporal：ForgeX 是一线制造商的先行者。经过实战验证。独家采购 6.457 亿美元。 2-3年内可复制。 PE 79%控制。 3-5年的窗口。",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "26",
            "FY2028": "43",
            "FY2029": "68",
            "FY2030": "107",
            "Change %": "+5.87%",
            "Entry": 62,
            "Total": 56
        },
        {
            "Rank": 30,
            "Ticker": "6830.TWO",
            "Name": "MSScorps (泛铨科技)",
            "EV Upside": 35,
            "Base": 83,
            "Port": "",
            "Current Price": 564.0,
            "Upside": "1.4x",
            "Position Type": "🔒 阻塞点\nCPO PIC漏光检查。在台湾/日本/美国获得专利。起诉恩利，拒绝许可。与客户共同开发 6 年。 VICR 模式双护城河（物理+法律）。",
            "Artifact Updated": "Jun 9 (rebuild)",
            "SuperCycle": "AI, CPO",
            "FY2027": "170",
            "FY2028": "804",
            "FY2029": "2,405",
            "FY2030": "4,943",
            "Change %": "+0.55%",
            "Entry": 14,
            "Total": 55
        },
        {
            "Rank": 31,
            "Ticker": "002371.SZ",
            "Name": "北方华创 NAURA",
            "EV Upside": 36,
            "Base": 82,
            "Port": "",
            "Current Price": 459.0,
            "Upside": "1.4x",
            "Position Type": "中国#1 WFE |长鑫存储资本支出",
            "Artifact Updated": "Jun 27",
            "SuperCycle": "Equipment, 国产替代",
            "FY2027": 435,
            "FY2028": 658,
            "FY2029": 811,
            "FY2030": 918,
            "Entry": 15,
            "Total": 55
        },
        {
            "Rank": 32,
            "Ticker": "4977.TW",
            "Name": "PCL Technologies (众达-KY)",
            "EV Upside": 39,
            "Base": 76,
            "Port": "",
            "Current Price": 184.5,
            "Upside": "1.5x",
            "Position Type": "⚡ 瓶颈",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, CPO, 1.6T",
            "FY2027": "111",
            "FY2028": "278",
            "FY2029": "596",
            "FY2030": "1,026",
            "Change %": "-7.73%",
            "Entry": 19,
            "Total": 53
        },
        {
            "Rank": 33,
            "Ticker": "AIXA.DE",
            "Name": "爱思强公司",
            "EV Upside": 34,
            "Base": 80,
            "Port": "",
            "Current Price": 52.12,
            "Upside": "1.4x",
            "Position Type": "🔒 阻塞点\n物理：70-90% MOCVD 份额——InP 外延记录工具。复合半成品的通用原语。 2026-2035+",
            "Artifact Updated": "Jun 16 (V1 lift + 25x)",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": 48,
            "FY2028": 74,
            "FY2029": 105,
            "FY2030": 134,
            "Change %": "-2.63%",
            "Entry": 14,
            "Total": 54
        },
        {
            "Rank": 34,
            "Ticker": "HPS-A.TO",
            "Name": "哈蒙德电力解决方案",
            "EV Upside": 38,
            "Base": 73,
            "Port": "",
            "Current Price": 324.67,
            "Upside": "1.5x",
            "Position Type": "⚡ 瓶颈\n需求：变压器的 DPA 需求下限。 #1 不适用，但市场竞争激烈。 2-3年的窗口。",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI",
            "FY2027": "C411",
            "FY2028": "C493",
            "FY2029": "C569",
            "FY2030": "C641",
            "Change %": "-2.41%",
            "Entry": 20,
            "Total": 52
        },
        {
            "Rank": 35,
            "Ticker": "EOS.AX",
            "Name": "光电系统",
            "EV Upside": 34,
            "Base": 78,
            "Port": "",
            "Current Price": 9.44,
            "Upside": "1.4x",
            "Position Type": "🔒 阻塞点\n物理：光速定向能 + 不受 ITAR 限制。每次射击的边际成本为零。 2026-2035+",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "Other",
            "FY2027": 4.7,
            "FY2028": 13.5,
            "FY2029": 23.4,
            "FY2030": 30.5,
            "Change %": "+4.13%",
            "Entry": 14,
            "Total": 52
        },
        {
            "Rank": 36,
            "Ticker": "JBL",
            "Name": "捷普公司",
            "EV Upside": 31,
            "Base": 68,
            "Port": "",
            "Current Price": 358.6,
            "Upside": "1.5x",
            "Position Type": "📊 受益人 |规则 10 上限 EMS",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI",
            "FY2027": 395,
            "FY2028": 522,
            "FY2029": 653,
            "FY2030": 791,
            "Entry": 16,
            "Total": 47
        },
        {
            "Rank": 37,
            "Ticker": "603986.SH",
            "Name": "GigaDevice 兆易创新",
            "EV Upside": 14,
            "Base": 82,
            "Port": "",
            "Current Price": 770.0,
            "Upside": "1.2x",
            "Position Type": "受益人|小众 DRAM + MCU",
            "Artifact Updated": "Jun 25",
            "SuperCycle": "Memory, China, edge AI",
            "FY2027": 480,
            "FY2028": 898,
            "FY2029": 1134,
            "FY2030": 1319,
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 38,
            "Ticker": "002409.SZ",
            "Name": "雅克科技 Yoke Technology",
            "EV Upside": 12,
            "Base": 82,
            "Port": "",
            "Current Price": 188.6,
            "Upside": "1.2x",
            "Position Type": "⚡ 瓶颈\nHBM前驱寡头+记忆材料年金",
            "Artifact Updated": "Jun 27 (demand-side capex-to-materials model, BOC Securities segments)",
            "SuperCycle": "AI, HBM, Memory, 国产替代",
            "FY2027": 157,
            "FY2028": 217,
            "FY2029": 284,
            "FY2030": 346,
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 39,
            "Ticker": "TSEM",
            "Name": "塔半导体",
            "EV Upside": 12,
            "Base": 82,
            "Port": "",
            "Current Price": 249.91,
            "Upside": "1.1x",
            "Position Type": "🔒 阻塞点\n资本+质量：~85% SiPh 代工 — 12-18 个月的重新认证障碍。 2026-2030+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI, CPO, 1.6T",
            "FY2027": "165",
            "FY2028": "285",
            "FY2029": "411",
            "FY2030": "528",
            "Change %": "-7.86%",
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 40,
            "Ticker": "CRDO",
            "Name": "信条科技",
            "EV Upside": 17,
            "Base": 75,
            "Port": "",
            "Current Price": 238.0,
            "Upside": "1.2x",
            "Position Type": "🔒 阻塞点\nIP：SerDes IP + ZeroFlap AEC — 100 倍可靠性 = 培训必备。多部门。 2026-2032+",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI, 1.6T, 800G",
            "FY2027": 151,
            "FY2028": 291,
            "FY2029": 448,
            "FY2030": 599,
            "Change %": "-8.79%",
            "Entry": 1,
            "Total": 45
        },
        {
            "Rank": 41,
            "Ticker": "BESI.AS",
            "Name": "BE半导体工业公司",
            "EV Upside": 11,
            "Base": 73,
            "Port": "",
            "Current Price": 252.02,
            "Upside": "1.2x",
            "Position Type": "🔒 阻塞点 |混合键合近乎垄断",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI, CPO",
            "FY2027": 192,
            "FY2028": 290,
            "FY2029": 358,
            "FY2030": 411,
            "Change %": "-2.25%",
            "Entry": 0,
            "Total": 44
        },
        {
            "Rank": 42,
            "Ticker": "BE",
            "Name": "布鲁姆能源",
            "EV Upside": 16,
            "Base": 70,
            "Port": "",
            "Current Price": 252.02,
            "Upside": "1.2x",
            "Position Type": "⚡ 瓶颈\n速度：90 天 SOFC 部署优势 - 随着电网连接的改善而逐渐消失。 2-4 年窗口。",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI",
            "FY2027": "166",
            "FY2028": "311",
            "FY2029": "476",
            "FY2030": "602",
            "Change %": "-5.80%",
            "Entry": 2,
            "Total": 43
        },
        {
            "Rank": 43,
            "Ticker": "000725.SZ",
            "Name": "京东方A BOE Technology",
            "EV Upside": 23,
            "Base": 65,
            "Port": "",
            "Current Price": 7.79,
            "Upside": "1.3x",
            "Position Type": "📊 受益人\n显示平台+玻璃芯基板可选",
            "Artifact Updated": "Jun 27 (new dive, glass-core substrate cross-read to LPKF/GLW)",
            "SuperCycle": "Display, OLED, Glass Substrate",
            "FY2027": 7.24,
            "FY2028": 10.5,
            "FY2029": 14.6,
            "FY2030": 18.1,
            "Entry": 9,
            "Total": 43
        },
        {
            "Rank": 44,
            "Ticker": "PNG.V",
            "Name": "克拉肯机器人公司",
            "EV Upside": 17,
            "Base": 75,
            "Port": "",
            "Current Price": 6.54,
            "Upside": "1.2x",
            "Position Type": "🔒 阻塞点\n资格：Sonardyne 水下定位黄金标准 - 数十年的质量惯性。 2026-2032+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "-",
            "FY2028": "C8.03",
            "FY2029": "C11.03",
            "FY2030": "C14.87",
            "Change %": "-2.02%",
            "Entry": 2,
            "Total": 46
        },
        {
            "Rank": 45,
            "Ticker": "AMD",
            "Name": "超微半导体公司",
            "EV Upside": 2,
            "Base": 78,
            "Port": "",
            "Current Price": 521.58,
            "Upside": "1.0x",
            "Position Type": "📊 受益人（系统层）",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI, CPO",
            "FY2027": 312,
            "FY2028": 536,
            "FY2029": 782,
            "FY2030": 992,
            "Entry": 0,
            "Total": 47
        },
        {
            "Rank": 46,
            "Ticker": "600584.SH",
            "Name": "长电科技 JCET Group",
            "EV Upside": -4,
            "Base": 75,
            "Port": "",
            "Current Price": 100.89,
            "Upside": "1.0x",
            "Position Type": "📊 受益人\n中国先进封装平台，而非全球瓶颈",
            "Artifact Updated": "Jun 27 (new dive, application-mix model)",
            "SuperCycle": "AI, Adv Pkg, Memory, 国産替代",
            "FY2027": 58,
            "FY2028": 96,
            "FY2029": 144,
            "FY2030": 199,
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 47,
            "Ticker": "NRGV",
            "Name": "能源库控股",
            "EV Upside": 16,
            "Base": 57,
            "Port": "",
            "Current Price": 4.21,
            "Upside": "1.3x",
            "Position Type": "⚡ 瓶颈\n能力：BESS部署者——没有护城河，有竞争力。 Asset Vault 循环模型未经验证。 2-3年的窗口。",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "1.79",
            "FY2028": "5.42",
            "FY2029": "10.50",
            "FY2030": "16.28",
            "Change %": "-9.54%",
            "Entry": 5,
            "Total": 36
        },
        {
            "Rank": 48,
            "Ticker": "VICR",
            "Name": "维科公司",
            "EV Upside": -8,
            "Base": 82,
            "Port": "",
            "Current Price": 326.93,
            "Upside": "0.9x",
            "Position Type": "🔒 阻塞点\n物理+法律：根据 CPO + ITC 专利终生进口禁令，需要 VPD。 2026-2035+",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "AI",
            "FY2027": "159",
            "FY2028": "296",
            "FY2029": "480",
            "FY2030": "647",
            "Change %": "-9.51%",
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 49,
            "Ticker": "ACMR",
            "Name": "ACM研究",
            "EV Upside": -6,
            "Base": 78,
            "Port": "",
            "Current Price": 116.34,
            "Upside": "0.9x",
            "Position Type": "⚡ 瓶颈\n中国WFE：湿法清洗+ECP+adv pkg+玻璃基板",
            "Artifact Updated": "Jun 27 (new dive, China WFE localization + panel-level ECP)",
            "SuperCycle": "AI, WFE, 国産替代, Glass Substrate",
            "FY2027": 68,
            "FY2028": 107,
            "FY2029": 149,
            "FY2030": 183,
            "Entry": 0,
            "Total": 47
        },
        {
            "Rank": 50,
            "Ticker": "STM",
            "Name": "意法半导体",
            "EV Upside": 2,
            "Base": 65,
            "Port": "",
            "Current Price": 71.42,
            "Upside": "1.0x",
            "Position Type": "规则 10 限制了 IDM。 SiC #1 (32.6%)、GaN、MEMS、STM32 MCU。数据中心$1B→$2B。没有任何细分市场通过规则 6。跨 800V/机器人/卫星/边缘人工智能的生态系统测试版。",
            "Artifact Updated": "Jun 15 (new dive)",
            "SuperCycle": "Other",
            "FY2027": 54,
            "FY2028": 74,
            "FY2029": 97,
            "FY2030": 118,
            "Entry": 0,
            "Total": 39
        },
        {
            "Rank": 51,
            "Ticker": "INTC",
            "Name": "英特尔公司",
            "EV Upside": -13,
            "Base": 80,
            "Port": "",
            "Current Price": 128.32,
            "Upside": "0.8x",
            "Position Type": "",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI, CPO",
            "FY2027": 57,
            "FY2028": 108,
            "FY2029": 164,
            "FY2030": 226,
            "Entry": 0,
            "Total": 48
        },
        {
            "Rank": 52,
            "Ticker": "300223.SZ",
            "Name": "北京君正 Ingenic",
            "EV Upside": -25,
            "Base": 83,
            "Port": "",
            "Current Price": 233.21,
            "Upside": "0.7x",
            "Position Type": "汽车级 SRAM #1 + 小众 DRAM",
            "Artifact Updated": "Jun 25",
            "SuperCycle": "Memory, Auto, AI Edge",
            "FY2027": 143,
            "FY2028": 164,
            "FY2029": 179,
            "FY2030": 195,
            "Entry": 0,
            "Total": 50
        },
        {
            "Rank": 53,
            "Ticker": "300666.SZ",
            "Name": "江丰电子 Konfoong Materials",
            "EV Upside": -26,
            "Base": 78,
            "Port": "",
            "Current Price": 354.78,
            "Upside": "0.7x",
            "Position Type": "⚡ 瓶颈\nPVD目标寡聚+ESC第二曲线",
            "Artifact Updated": "Jun 27 (rebuilt: 276M shares, ¥355, ESC 65% GM, FY28 ¥236)",
            "SuperCycle": "AI, Memory, 国産替代, ESC",
            "FY2027": 136,
            "FY2028": 236,
            "FY2029": 350,
            "FY2030": 460,
            "Entry": 0,
            "Total": 47
        },
        {
            "Rank": 54,
            "Ticker": "688409.SH",
            "Name": "富创精密 Fortune Precision",
            "EV Upside": -22,
            "Base": 75,
            "Port": "",
            "Current Price": 298.0,
            "Upside": "0.7x",
            "Position Type": "📊 受益人\n中国WFE精密零件+气体输送子系统",
            "Artifact Updated": "Jun 27 (new dive, WFE subsystem/parts layer)",
            "SuperCycle": "AI, WFE Subsystems, 国産替代",
            "FY2027": 94,
            "FY2028": 211,
            "FY2029": 362,
            "FY2030": 523,
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 55,
            "Ticker": "SMTC",
            "Name": "森泰克公司",
            "EV Upside": -19,
            "Base": 72,
            "Port": "",
            "Current Price": 149.75,
            "Upside": "0.7x",
            "Position Type": "⚡ 瓶颈-相邻| 224G光IC",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI, CPO, 800G, 1.6T",
            "FY2027": 65,
            "FY2028": 111,
            "FY2029": 160,
            "FY2030": 208,
            "Entry": 0,
            "Total": 43
        },
        {
            "Rank": 56,
            "Ticker": "MRVL",
            "Name": "迈维尔科技",
            "EV Upside": -30,
            "Base": 82,
            "Port": "",
            "Current Price": 252.04,
            "Upside": "0.6x",
            "Position Type": "🔒 阻塞点\n双头垄断：定制 ASIC——只有 MRVL + Broadcom 设计超大规模人工智能芯片。 2-3年设计周期=锁定。亚马逊、谷歌、微软、Meta。 2026-2035+",
            "Artifact Updated": "Jun 27 (v4.2: 30x→20x, Base 78→82%, CXL/TPU vectors)",
            "SuperCycle": "AI, CPO, 1.6T, 800G",
            "FY2027": 88,
            "FY2028": 159,
            "FY2029": 248,
            "FY2030": 347,
            "Change %": "-3.18%",
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 57,
            "Ticker": "688008.SH",
            "Name": "澜起科技 Montage Technology",
            "EV Upside": -31,
            "Base": 82,
            "Port": "",
            "Current Price": 296.06,
            "Upside": "0.6x",
            "Position Type": "⚡ 瓶颈\n中国内存接口/CXL/PCIe互连平台",
            "Artifact Updated": "Jun 27 (new dive, China MRVL/ALAB analogue for memory-wall)",
            "SuperCycle": "AI, CXL, Memory Interface, 国産替代",
            "FY2027": 110,
            "FY2028": 185,
            "FY2029": 261,
            "FY2030": 327,
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 58,
            "Ticker": "002484.SZ",
            "Name": "江海股份 Jianghai Capacitor",
            "EV Upside": -23,
            "Base": 68,
            "Port": "",
            "Current Price": 104.82,
            "Upside": "0.7x",
            "Position Type": "📊 受益人\nAI机架式电力电容器平台",
            "Artifact Updated": "Jun 27 (new dive, AI power-density + supercap optionality)",
            "SuperCycle": "AI Power, Passive Components",
            "FY2027": 46,
            "FY2028": 69,
            "FY2029": 91,
            "FY2030": 110,
            "Entry": 0,
            "Total": 41
        },
        {
            "Rank": 59,
            "Ticker": "688072.SH",
            "Name": "拓荆科技 Piotech",
            "EV Upside": -29,
            "Base": 80,
            "Port": "",
            "Current Price": 832.0,
            "Upside": "0.6x",
            "Position Type": "⚡ 瓶颈\n中国薄膜沉积+混合键合WFE",
            "Artifact Updated": "Jun 27 (new dive, AMEC deposition pair + hybrid bonding)",
            "SuperCycle": "AI, WFE, CVD/ALD, 国産替代",
            "FY2027": 264,
            "FY2028": 529,
            "FY2029": 870,
            "FY2030": 1332,
            "Entry": 0,
            "Total": 48
        },
        {
            "Rank": 60,
            "Ticker": "300408.SZ",
            "Name": "三环集团",
            "EV Upside": -28,
            "Base": 78,
            "Port": "",
            "Current Price": 160.05,
            "Upside": "0.6x",
            "Position Type": "⚡/🔒 混合\n光纤陶瓷插芯全球垄断70-80%（85%+ MPO/MT）。中国增长最快的MLCC，粉末100%自供。双人工智能论文。 H股港交所上市待定",
            "Artifact Updated": "Jun 24",
            "SuperCycle": "AI, CPO",
            "FY2027": 75,
            "FY2028": 103,
            "FY2029": 127,
            "FY2030": 160,
            "Entry": 0,
            "Total": 47
        },
        {
            "Rank": 61,
            "Ticker": "688120.SH",
            "Name": "华海清科 Hwatsing",
            "EV Upside": -28,
            "Base": 78,
            "Port": "",
            "Current Price": 316.32,
            "Upside": "0.6x",
            "Position Type": "⚡ 瓶颈\n中国CMP+面板级CMP+HBM/玻璃基板",
            "Artifact Updated": "Jun 27 (new dive, CMP champion + panel-level glass substrate)",
            "SuperCycle": "AI, WFE, CMP, 国産替代",
            "FY2027": 113,
            "FY2028": 204,
            "FY2029": 333,
            "FY2030": 461,
            "Entry": 0,
            "Total": 47
        },
        {
            "Rank": 62,
            "Ticker": "GLW",
            "Name": "康宁",
            "EV Upside": -16,
            "Base": 65,
            "Port": "",
            "Current Price": 221.05,
            "Upside": "0.7x",
            "Position Type": "规则 10 |玻璃科学+AI光学",
            "Artifact Updated": "Jun 25",
            "SuperCycle": "Photonics, Glass, CPO",
            "FY2027": 126,
            "FY2028": 165,
            "FY2029": 209,
            "FY2030": 257,
            "Entry": 0,
            "Total": 39
        },
        {
            "Rank": 63,
            "Ticker": "300285.SZ",
            "Name": "Sinocera (国瓷材料)",
            "EV Upside": -30,
            "Base": 75,
            "Port": "",
            "Current Price": 102.81,
            "Upside": "0.6x",
            "Position Type": "",
            "Artifact Updated": "Jun 16 (TF content 7.3x)",
            "SuperCycle": "AI",
            "FY2027": 34,
            "FY2028": 62,
            "FY2029": 78,
            "FY2030": 96,
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 64,
            "Ticker": "SHMD",
            "Name": "施密德集团",
            "EV Upside": -9,
            "Base": 53,
            "Port": "",
            "Current Price": 5.72,
            "Upside": "0.8x",
            "Position Type": "❌ 失败带\nGlass-line equipment integrator — owns the LINE not the CHEMISTRY (Atotech/MKS). Delisting proceeding + negative GM + active dilution. Pre-registered upgrade path: 20-F clear / named glass order / CpK 1.33 gate",
            "Artifact Updated": "Jun 12 (new dive)",
            "SuperCycle": "AI, CPO",
            "FY2027": 1.78,
            "FY2028": 4.7,
            "FY2029": 7.13,
            "FY2030": 9.11,
            "Entry": 0,
            "Total": 32
        },
        {
            "Rank": 65,
            "Ticker": "688012.SH",
            "Name": "中微公司 AMEC",
            "EV Upside": -40,
            "Base": 82,
            "Port": "",
            "Current Price": 456.69,
            "Upside": "0.5x",
            "Position Type": "⚡ 瓶颈\n中国高端刻蚀+沉积WFE平台",
            "Artifact Updated": "Jun 27 (new dive, China etch champion + thin-film expansion)",
            "SuperCycle": "AI, WFE, Etch, 国産替代",
            "FY2027": 135,
            "FY2028": 234,
            "FY2029": 354,
            "FY2030": 493,
            "Entry": 0,
            "Total": 49
        },
        {
            "Rank": 66,
            "Ticker": "002428.SZ",
            "Name": "云南锗业 Yunnan Germanium (InP)",
            "EV Upside": -34,
            "Base": 72,
            "Port": "",
            "Current Price": 120.48,
            "Upside": "0.5x",
            "Position Type": "🔒 阻塞点 |国内InP垄断|接近于零的电动势",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI, CPO, 800G, 1.6T",
            "FY2027": 34,
            "FY2028": 64,
            "FY2029": 100,
            "FY2030": 127,
            "Entry": 0,
            "Total": 43
        },
        {
            "Rank": 67,
            "Ticker": "1888.HK",
            "Name": "建滔积层板",
            "EV Upside": -35,
            "Base": 65,
            "Port": "",
            "Current Price": 98.55,
            "Upside": "0.5x",
            "Position Type": "⚡ 瓶颈 |覆铜板周期性定价|电动汽车",
            "Artifact Updated": "Jun 19",
            "SuperCycle": "AI",
            "FY2027": 33,
            "FY2028": 46,
            "FY2029": 42,
            "FY2030": 36,
            "Change %": "+2.48%",
            "Entry": 0,
            "Total": 39
        },
        {
            "Rank": 68,
            "Ticker": "ALAB",
            "Name": "阿斯特拉实验室",
            "EV Upside": -45,
            "Base": 75,
            "Port": "",
            "Current Price": 391.74,
            "Upside": "0.4x",
            "Position Type": "⚡ 瓶颈\n时间：PCIe Gen 6 先行者。 80%的AI服务器渗透率。基于标准=竞争对手迎头赶上。亚马逊$6.5B 认股权证。 2-3年的窗口。",
            "Artifact Updated": "Jun 27 (v4.2 audit: 25x→20x, FY28 $195→$156)",
            "SuperCycle": "AI, 1.6T, 800G",
            "FY2027": 100,
            "FY2028": 156,
            "FY2029": 217,
            "FY2030": 278,
            "Change %": "-6.70%",
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 69,
            "Ticker": "ARM",
            "Name": "安谋控股",
            "EV Upside": -46,
            "Base": 75,
            "Port": "",
            "Current Price": 334.27,
            "Upside": "0.4x",
            "Position Type": "🔒 阻塞点\nISA 垄断——全世界的软件都编译为 Arm。 50% 超大规模 CPU，~100% DPU/SmartNIC。 AGI CPU 商用坡道。 RISC-V = 证伪测试",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI",
            "FY2027": 85,
            "FY2028": 128,
            "FY2029": 192,
            "FY2030": 275,
            "Change %": "+0.82%",
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 70,
            "Ticker": "002384.SZ",
            "Name": "东山精密 Dongshan Precision",
            "EV Upside": -41,
            "Base": 67,
            "Port": "",
            "Current Price": 260.32,
            "Upside": "0.4x",
            "Position Type": "📊 受益人 |规则10上限+中国-3 |电动汽车",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI, 800G, 1.6T",
            "FY2027": 61,
            "FY2028": 100,
            "FY2029": 145,
            "FY2030": 190,
            "Entry": 0,
            "Total": 40
        },
        {
            "Rank": 71,
            "Ticker": "OUST",
            "Name": "驱逐者公司",
            "EV Upside": -49,
            "Base": 75,
            "Port": "",
            "Current Price": 42.02,
            "Upside": "0.3x",
            "Position Type": "⚡ 瓶颈\n物理AI感知平台（原🔒，降级规则6）",
            "Artifact Updated": "Jun 27 (v4.2 audit: shares 180M→72M, 30x→20x, Base 82→75%)",
            "SuperCycle": "Other",
            "FY2027": 0,
            "FY2028": 14.6,
            "FY2029": 44.7,
            "FY2030": 86.5,
            "Change %": "-16.41%",
            "Entry": 0,
            "Total": 45
        },
        {
            "Rank": 72,
            "Ticker": "PL",
            "Name": "星球实验室",
            "EV Upside": -49,
            "Base": 67,
            "Port": "",
            "Current Price": 27.07,
            "Upside": "0.3x",
            "Position Type": "⚡ 瓶颈\n监管：非机密情报领域——有效的护城河，但卫星舰队会贬值。 2-3年的窗口。",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "0.78",
            "FY2028": "7.10",
            "FY2029": "17.28",
            "FY2030": "34.35",
            "Change %": "-1.36%",
            "Entry": 0,
            "Total": 40
        },
        {
            "Rank": 73,
            "Ticker": "WOLF",
            "Name": "狼速",
            "EV Upside": -39,
            "Base": 55,
            "Port": "",
            "Current Price": 45.97,
            "Upside": "0.3x",
            "Position Type": "",
            "Artifact Updated": "Jun 11 (restructure)",
            "SuperCycle": "Other",
            "FY2027": "neg",
            "FY2028": "13",
            "FY2029": "59",
            "FY2030": "114",
            "Entry": 0,
            "Total": 33
        },
        {
            "Rank": 74,
            "Ticker": "600330.SH",
            "Name": "天通股份 Tiantong (LN/TFLN)",
            "EV Upside": -44,
            "Base": 57,
            "Port": "",
            "Current Price": 32.75,
            "Upside": "0.2x",
            "Position Type": "❌ 失败 |治理 + 预收入 + 规则 10",
            "Artifact Updated": "Jun 17",
            "SuperCycle": "AI, CPO, 1.6T",
            "FY2027": 2.2,
            "FY2028": 7.3,
            "FY2029": 13.2,
            "FY2030": 18.7,
            "Entry": 0,
            "Total": 34
        }
    ]
};